# Generated by Django 4.0.5 on 2022-06-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.CharField(max_length=30)),
                ('temperature', models.IntegerField()),
                ('pressure', models.BigIntegerField()),
                ('humidity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('visibility', models.CharField(max_length=30)),
            ],
        ),
    ]
